pub mod agent;
pub mod agents_roster;
pub mod auto_setup;
pub mod brain;
pub mod character;
pub mod chat;
pub mod coding;
pub mod consolidation;
pub mod ingest;
pub mod docker;
pub mod emotion;
pub mod gitnexus;
pub mod identity;
pub mod link;
pub mod mcp;
pub mod memory;
pub mod messaging;
pub mod package;
pub mod persona;
pub mod plugins;
pub mod quest;
pub mod registry;
pub mod routing;
pub mod sandbox;
pub mod settings;
pub mod streaming;
pub mod translation;
pub mod user_models;
pub mod vision;
pub mod voice;
pub mod vscode;
pub mod window;

#[cfg(test)]
mod ipc_contract_tests;
