//! Git hook installer for branch-overlay code-intelligence (Chunk 45.2).
//!
//! Generates POSIX shell scripts for `post-checkout`, `post-merge`, and
//! `post-commit` that POST to the local MCP server to trigger incremental
//! overlay syncs. Scripts always exit 0 so git is never blocked.
//!
//! The hook scripts are generated by TerranSoul and not vendored from any
//! third-party project.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use thiserror::Error;

// ─── Error ──────────────────────────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum HookError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Not a git repository: {0}")]
    NotGitRepo(String),
    #[error("hooks directory not found: {0}")]
    NoHooksDir(String),
}

// ─── Types ──────────────────────────────────────────────────────────────────

/// Result of installing hooks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookInstallResult {
    pub hooks_dir: String,
    pub installed: Vec<String>,
    pub skipped: Vec<String>,
}

/// Which MCP port to target.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum McpTarget {
    /// Release app (port 7421).
    Release,
    /// Dev app (port 7422).
    Dev,
    /// Headless/pet mode (port 7423).
    Headless,
}

impl McpTarget {
    pub fn port(self) -> u16 {
        match self {
            Self::Release => 7421,
            Self::Dev => 7422,
            Self::Headless => 7423,
        }
    }
}

// ─── Public API ─────────────────────────────────────────────────────────────

/// Install TerranSoul code-intelligence git hooks into a repository.
///
/// If `force` is true, existing hooks are overwritten. Otherwise existing
/// hooks are skipped (reported in `skipped`).
///
/// The `token_path` is the path to the MCP token file (e.g. `.vscode/.mcp-token`).
pub fn install_hooks(
    repo_path: &Path,
    target: McpTarget,
    token_path: &str,
    force: bool,
) -> Result<HookInstallResult, HookError> {
    let git_dir = find_git_dir(repo_path)?;
    let hooks_dir = git_dir.join("hooks");

    if !hooks_dir.exists() {
        fs::create_dir_all(&hooks_dir)?;
    }

    let port = target.port();
    let mut result = HookInstallResult {
        hooks_dir: hooks_dir.to_string_lossy().to_string(),
        installed: Vec::new(),
        skipped: Vec::new(),
    };

    let hooks = [
        ("post-checkout", generate_post_checkout(port, token_path)),
        ("post-merge", generate_post_merge(port, token_path)),
        ("post-commit", generate_post_commit(port, token_path)),
    ];

    for (name, content) in &hooks {
        let hook_path = hooks_dir.join(name);
        if hook_path.exists() && !force {
            // Check if it's ours (has our marker).
            let existing = fs::read_to_string(&hook_path).unwrap_or_default();
            if !existing.contains("# TerranSoul code-intelligence hook") {
                result.skipped.push(name.to_string());
                continue;
            }
        }

        fs::write(&hook_path, content)?;
        // Make executable on Unix.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = fs::Permissions::from_mode(0o755);
            fs::set_permissions(&hook_path, perms)?;
        }
        result.installed.push(name.to_string());
    }

    Ok(result)
}

/// Remove TerranSoul hooks from a repository (only removes our hooks).
pub fn uninstall_hooks(repo_path: &Path) -> Result<Vec<String>, HookError> {
    let git_dir = find_git_dir(repo_path)?;
    let hooks_dir = git_dir.join("hooks");
    let mut removed = Vec::new();

    for name in &["post-checkout", "post-merge", "post-commit"] {
        let hook_path = hooks_dir.join(name);
        if hook_path.exists() {
            let content = fs::read_to_string(&hook_path).unwrap_or_default();
            if content.contains("# TerranSoul code-intelligence hook") {
                fs::remove_file(&hook_path)?;
                removed.push(name.to_string());
            }
        }
    }

    Ok(removed)
}

// ─── Hook script generation ─────────────────────────────────────────────────

fn generate_post_checkout(port: u16, token_path: &str) -> String {
    format!(
        r#"#!/bin/sh
# TerranSoul code-intelligence hook — post-checkout
# Generated by TerranSoul. Do not edit manually.
# This hook notifies the local MCP server of branch changes.
# It always exits 0 so git operations are never blocked.

PREV_SHA="$1"
NEW_SHA="$2"
BRANCH_FLAG="$3"

# Only act on branch checkouts (flag=1), not file checkouts.
if [ "$BRANCH_FLAG" != "1" ]; then
    exit 0
fi

# Skip if prev == new (no actual change).
if [ "$PREV_SHA" = "$NEW_SHA" ]; then
    exit 0
fi

TOKEN=""
if [ -f "{token_path}" ]; then
    TOKEN=$(cat "{token_path}")
fi

curl -s -X POST "http://127.0.0.1:{port}/hooks/branch-sync" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TOKEN" \
    -d "{{"prev":"$PREV_SHA","new":"$NEW_SHA"}}" \
    >/dev/null 2>&1 || true

exit 0
"#
    )
}

fn generate_post_merge(port: u16, token_path: &str) -> String {
    format!(
        r#"#!/bin/sh
# TerranSoul code-intelligence hook — post-merge
# Generated by TerranSoul. Do not edit manually.
# Notifies MCP server that a merge completed so overlay can update.
# Always exits 0.

# ORIG_HEAD is the tip before merge; HEAD is the new merge commit.
PREV_SHA=$(git rev-parse ORIG_HEAD 2>/dev/null || echo "")
NEW_SHA=$(git rev-parse HEAD 2>/dev/null || echo "")

if [ -z "$PREV_SHA" ] || [ -z "$NEW_SHA" ]; then
    exit 0
fi

TOKEN=""
if [ -f "{token_path}" ]; then
    TOKEN=$(cat "{token_path}")
fi

curl -s -X POST "http://127.0.0.1:{port}/hooks/branch-sync" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TOKEN" \
    -d "{{"prev":"$PREV_SHA","new":"$NEW_SHA"}}" \
    >/dev/null 2>&1 || true

exit 0
"#
    )
}

fn generate_post_commit(port: u16, token_path: &str) -> String {
    format!(
        r#"#!/bin/sh
# TerranSoul code-intelligence hook — post-commit
# Generated by TerranSoul. Do not edit manually.
# Notifies MCP server of the new commit for overlay indexing.
# Always exits 0.

COMMIT_SHA=$(git rev-parse HEAD 2>/dev/null || echo "")

if [ -z "$COMMIT_SHA" ]; then
    exit 0
fi

TOKEN=""
if [ -f "{token_path}" ]; then
    TOKEN=$(cat "{token_path}")
fi

curl -s -X POST "http://127.0.0.1:{port}/hooks/index-commit" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TOKEN" \
    -d "{{"commit":"$COMMIT_SHA"}}" \
    >/dev/null 2>&1 || true

exit 0
"#
    )
}

// ─── Helpers ────────────────────────────────────────────────────────────────

/// Find the .git directory for a repository path.
fn find_git_dir(repo_path: &Path) -> Result<PathBuf, HookError> {
    let git_path = repo_path.join(".git");
    if git_path.is_dir() {
        return Ok(git_path);
    }
    // Support git worktrees: .git might be a file pointing to the real gitdir.
    if git_path.is_file() {
        let content = fs::read_to_string(&git_path)?;
        if let Some(dir) = content.strip_prefix("gitdir: ") {
            let dir = dir.trim();
            let resolved = if Path::new(dir).is_absolute() {
                PathBuf::from(dir)
            } else {
                repo_path.join(dir)
            };
            if resolved.is_dir() {
                return Ok(resolved);
            }
        }
    }
    Err(HookError::NotGitRepo(
        repo_path.to_string_lossy().to_string(),
    ))
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn setup_fake_repo() -> TempDir {
        let dir = TempDir::new().unwrap();
        let git_dir = dir.path().join(".git");
        fs::create_dir_all(git_dir.join("hooks")).unwrap();
        dir
    }

    #[test]
    fn install_creates_three_hooks() {
        let dir = setup_fake_repo();
        let result =
            install_hooks(dir.path(), McpTarget::Headless, ".vscode/.mcp-token", false).unwrap();

        assert_eq!(result.installed.len(), 3);
        assert!(result.skipped.is_empty());

        // Verify files exist and contain our marker.
        for hook in &["post-checkout", "post-merge", "post-commit"] {
            let path = dir.path().join(".git/hooks").join(hook);
            assert!(path.exists());
            let content = fs::read_to_string(&path).unwrap();
            assert!(content.contains("# TerranSoul code-intelligence hook"));
            assert!(content.contains("exit 0"));
            assert!(content.contains("7423")); // headless port
        }
    }

    #[test]
    fn install_skips_foreign_hooks() {
        let dir = setup_fake_repo();
        // Write a foreign hook.
        let hook_path = dir.path().join(".git/hooks/post-checkout");
        fs::write(&hook_path, "#!/bin/sh\necho 'foreign hook'\n").unwrap();

        let result =
            install_hooks(dir.path(), McpTarget::Dev, ".vscode/.mcp-token", false).unwrap();

        assert_eq!(result.skipped, vec!["post-checkout"]);
        assert_eq!(result.installed.len(), 2); // post-merge + post-commit

        // Foreign hook untouched.
        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains("foreign hook"));
    }

    #[test]
    fn install_force_overwrites_foreign_hooks() {
        let dir = setup_fake_repo();
        let hook_path = dir.path().join(".git/hooks/post-checkout");
        fs::write(&hook_path, "#!/bin/sh\necho 'foreign'\n").unwrap();

        let result =
            install_hooks(dir.path(), McpTarget::Release, ".vscode/.mcp-token", true).unwrap();

        assert_eq!(result.installed.len(), 3);
        assert!(result.skipped.is_empty());

        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains("# TerranSoul code-intelligence hook"));
        assert!(content.contains("7421")); // release port
    }

    #[test]
    fn uninstall_removes_our_hooks_only() {
        let dir = setup_fake_repo();
        // Install our hooks.
        install_hooks(dir.path(), McpTarget::Headless, ".vscode/.mcp-token", false).unwrap();

        // Write a foreign hook (different name won't be touched).
        let pre_push = dir.path().join(".git/hooks/pre-push");
        fs::write(&pre_push, "#!/bin/sh\necho 'keep me'\n").unwrap();

        let removed = uninstall_hooks(dir.path()).unwrap();
        assert_eq!(removed.len(), 3);

        // Our hooks gone.
        assert!(!dir.path().join(".git/hooks/post-checkout").exists());

        // Foreign hook still there.
        assert!(pre_push.exists());
    }

    #[test]
    fn install_idempotent() {
        let dir = setup_fake_repo();
        install_hooks(dir.path(), McpTarget::Headless, ".vscode/.mcp-token", false).unwrap();

        // Install again — our own hooks get overwritten (same marker).
        let result =
            install_hooks(dir.path(), McpTarget::Headless, ".vscode/.mcp-token", false).unwrap();
        assert_eq!(result.installed.len(), 3);
        assert!(result.skipped.is_empty());
    }

    #[test]
    fn post_checkout_script_structure() {
        let script = generate_post_checkout(7423, ".vscode/.mcp-token");
        assert!(script.starts_with("#!/bin/sh"));
        assert!(script.contains("BRANCH_FLAG=\"$3\""));
        assert!(script.contains("branch-sync"));
        assert!(script.contains("|| true"));
        assert!(script.ends_with("exit 0\n"));
    }

    #[test]
    fn post_commit_targets_index_commit_endpoint() {
        let script = generate_post_commit(7422, "token.txt");
        assert!(script.contains("/hooks/index-commit"));
        assert!(script.contains("7422"));
        assert!(script.contains("token.txt"));
    }

    #[test]
    fn find_git_dir_errors_on_non_repo() {
        let dir = TempDir::new().unwrap();
        let err = find_git_dir(dir.path()).unwrap_err();
        assert!(matches!(err, HookError::NotGitRepo(_)));
    }

    #[test]
    fn find_git_dir_worktree_support() {
        let dir = TempDir::new().unwrap();
        let actual_git = dir.path().join("actual-git");
        fs::create_dir_all(&actual_git).unwrap();
        // Write .git file pointing to actual gitdir.
        fs::write(
            dir.path().join(".git"),
            format!("gitdir: {}", actual_git.to_string_lossy()),
        )
        .unwrap();

        let result = find_git_dir(dir.path()).unwrap();
        assert_eq!(result, actual_git);
    }
}
