-- 2026-05-07: refresh stale Phase 41 audit/result rows in existing MCP DBs.

UPDATE memories
SET content = 'MILLION-KNOWLEDGE CRUD AUDIT STATE (updated 2026-05-07): TerranSoul memory store has SQLite WAL + tuned Phase 41.1 PRAGMAs, V15 schema with eviction-friendly indexes, usearch HNSW with brute-force fallback, capacity eviction, embedding retry queue, memory_versions, contradiction detection, semantic chunker, late chunking, contextual retrieval, Criterion 10k/1M bench, ingest semaphore, Phase 41.4 transactional add_many, Phase 41.2 per-op metrics, and Phase 41.3 bounded CRUD benchmark sections. Resolved from the original audit: PRAGMA defaults, missing add_many, missing per-op metrics, and unbounded benchmark stalls. Remaining 1M+ optimization work: route high-level ingest fully through bulk APIs, remove get_all/get_with_embeddings from hot search paths, re-embed and tombstone ANN entries on content update, reduce HNSW save-every-50-op churn, support per-model/dim ANN registries, add cursor reads/quantization/tombstone compaction, and verify FTS/KG indexes at 1M rows.'
WHERE content LIKE 'MILLION-KNOWLEDGE CRUD AUDIT (2026-05-06):%';

UPDATE memories
SET content = 'PHASE 41 RESULT (2026-05-07): chunks 41.1 (SQLite PRAGMA tuning), 41.4 (transactional add_many), 41.2 (per-op metrics), and 41.3 (extended CRUD bench + timeout guards) shipped. Measured on commodity dev hardware via cargo bench --bench million_memory: 10k smoke write 0.04s @ 244,657 rows/s, read 0.01s @ 939,956 rows/s. 1M CRUD-only runs (TS_BENCH_SCALES=1000000 TS_BENCH_CRUD_ONLY=1) keep the headline target green; latest bounded run wrote 1M in 7.27s @ 137,521 rows/s and read 1M in 2.13s @ 469,036 rows/s, with update 2.58s @ 387,042 rows/s and mixed 10k ops in 160.03s. Million-scale benchmark delete is skipped because secondary-index maintenance dominates wall-clock and is not part of the write/read SLO. Remaining Phase 41 chunks (41.5 cursor reads, 41.6 re-embed on update, 41.7 worker concurrency, 41.8 multi-model embeddings, 41.9-41.11 ANN scaling, 41.12-41.13 indexes/KG, 41.14-41.15 sharding/snapshot) remain valuable for production hardening but are no longer blocking the headline throughput goal.'
WHERE content LIKE 'PHASE 41 RESULT (2026-05-07):%';
